---
#
# Ansible managed
#
repository:
  description: Setup the [Bareos](https://www.bareos.com/) repositories.
  homepage: https://robertdebock.nl/
  topics: backup, bareos, infrastructure, linux, storage, system, tools, ansible, molecule, playbook
